services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "9001:9001"
    environment:
      - API_KEY=${API_KEY}
      - QUANTUM_BACKEND=${QUANTUM_BACKEND:-simulator}
      - QUANTUM_N_QUBITS=${QUANTUM_N_QUBITS:-4}
    command: uv run uvicorn main:app --host 0.0.0.0 --port 9001
    volumes:
      - .:/app
    network_mode: host

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    env_file:
      - .env
    command:
      - tunnel
      - --no-autoupdate
      - run
    network_mode: host
